# Generated by Django 4.1.7 on 2023-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0004_alter_maintenance_date_maintenance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="type_machine",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "Mac - Run MacOS"),
                    ("serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - To maintains and connect servers"),
                ],
                max_length=100,
            ),
        ),
    ]
