# Generated by Django 4.1.7 on 2023-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0005_alter_machine_type_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="statut",
            field=models.CharField(
                choices=[
                    ("indisponible", "Défaillant"),
                    ("utilisable", "Bon état"),
                    ("En maintenance", "En maintenance"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type_machine",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("PC", "PC - Run lunix"),
                    ("Mac", "Mac - Run MacOS"),
                    ("outils", "imprimantes"),
                    ("serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - To maintains and connect servers"),
                ],
                max_length=100,
            ),
        ),
    ]
